<pre>--- Summary ---
Tests passed: 0 out of 4

--- Details ---
Test #0: failed 
Test case description: ML4T-220
Traceback:
  File "grade_strategy_learner.py", line 251, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'ML4T-220', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'ML4T-220', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: clean
    benchmark: 1.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.00257478) did not beat benchmark (1.0)
  out-sample return (0.06083202) did not beat benchmark (1.0)

Test #1: failed 
Test case description: AAPL
Traceback:
  File "grade_strategy_learner.py", line 251, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'AAPL', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'AAPL', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: stock
    benchmark: 0.1582
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (0.071) did not beat benchmark (0.1582)

Test #2: failed 
Test case description: SINE_FAST_NOISE
Traceback:
  File "grade_strategy_learner.py", line 251, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'SINE_FAST_NOISE', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'SINE_FAST_NOISE', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: noisy
    benchmark: 2.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.143347436989) did not beat benchmark (2.0)

Test #3: failed 
Test case description: UNH - In sample
Traceback:
  File "grade_strategy_learner.py", line 251, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'UNH', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'UNH', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: stock
    benchmark: -0.2524
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.2878) did not beat benchmark (-0.2524)

</pre>
